; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build options
build_flags = 
    -DUSER_SETUP_LOADED=1
    -DILI9341_2_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=4
    -DTFT_BL=21
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=16000000
    -DUSE_HSPI_PORT=1
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Library dependencies
lib_deps = 
    https://github.com/Bodmer/TFT_eSPI
    https://github.com/Links2004/arduinoWebSockets
    ricmoo/QRCode
    ; WiFi (built-in)
    ; WebServer (built-in)
    ; Preferences (built-in)
    ; Wire (built-in)
    ; mbedtls (built-in)

; Upload options
upload_speed = 921600
